version: "3.3"
services:
  sentc:
    image: sentc/api:${SENTC_VERSION}
    restart: always
    command: sh -c "sleep 10 && /sentc_api_init && /server_api_all"
    ports:
      - "3002:3002"
    env_file:
      - ../sentc.env
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DB}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      LOCAL_STORAGE_PATH: /var/www/storage
    volumes:
      - ../storage:/var/www/storage